name: Release

on:
  push:
    branches:
      - master
      - next
      - rc
  workflow_dispatch:

jobs:
  release:
    name: Release / Node ${{ matrix.node }}
    strategy:
      matrix:
        node: ['18']

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: |
          npm ci
          npm run build

      - name: Create a release for @supabase/auth-js
        run: npx semantic-release -r 'https://github.com/supabase/gotrue-js.git'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create a release for @supabase/gotrue-js
        run: |
          for f in package.json package-lock.json
          do
            sed -i '' 's|\(["/]\)auth-js|\1gotrue-js|g' "$f"
          done

          npx semantic-release -r 'https://github.com/supabase/gotrue-js.git'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
